### ISSUE TITLE
hawtio-bom 4.0.0.redhat-00040

### ISSUE THREAD

**Issue by ddatsh** [jboss-fuse/hawtio-examples#1]
[ERROR] Non-resolvable import POM: Could not find artifact io.hawt:hawtio-bom:pom:4.0.0.redhat-00040 in redhat-ga-repository (https://maven.repository.redhat.com/ga/)

https://maven.repository.redhat.com/ga
https://maven.repository.redhat.com/earlyaccess/all/io/hawt/hawtio-bom/maven-metadata.xml
only  2.0.0*

**Comment by tadayosi** [comment]
@ddatsh It's not officially released yet. We are working hard to deliver it to you soon. Please be patient.
